name: Get updated TTU sports articles

on:
    schedule:
        - cron: '0 0 * * *'  # Runs daily at midnight (UTC)
    workflow_dispatch:  # Allows manual runs

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false  # Disables default authentication

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run script
              run: python rss_sports_feed.py  # Make sure this script updates rss_feed.json

            - name: Configure Git
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            - name: Commit changes
              run: |
                  git add rss_feed.json
                  git diff --cached --quiet || git commit -m "Update sports articles"
              
            - name: Push changes
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/YOUR_USERNAME/YOUR_REPO.git
                  git push origin main
